### ISSUE TITLE
Work with Logitech circle view doorbell?

### ISSUE THREAD

**Issue by paradoxgrowth** [klanchman/homebridge-logi-circle-controls#41] opened 2022-05-22 23:00 UTC
Hi and thanks so much for writing this plugin!

just wanted to know if this works for the circle view doorbell as well. I saw in HomeKit there was a control to turn the actual doorbell off. I would love to be able to put that on a timer so no one wakes my baby during nap time. 

Thanks again

**Comment by klanchman** [comment] 2022-05-24 03:41
Hi 👋  — unfortunately this plugin only works with older Logi Circle cameras through Logitech's web service, not HomeKit Secure Video devices like the Logi Circle View Camera and Doorbell. Moreover, the chime setting might not be something that Homebridge can actually edit. (I'm only speculating, though.)

My recommendation for now is to send feedback to Apple at https://www.apple.com/feedback/ (or possibly https://feedbackassistant.apple.com) to suggest the ability to automate the chime state in the Home app 😄 

For HomeKit Secure Video support in general, I'll point to #19.
The summary is it would end up in a separate plugin, if it's possible at all.

I'm going to close this as a duplicate of #19, but let me know if you have any other questions!

**Closed as not planned by klanchman** 2022-05-24 03:41 UTC
Labels: question
